[versions]
agp = "8.7.3"
cicerone = "7.1"
coil = "3.0.4"
dexter = "6.2.2"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
loadingButtonAndroid = "2.3.0"
material = "1.12.0"

koinVersion="3.4.3"
navigationFragmentKtx = "2.8.5"
pinview = "1.4.4"
retrofitVersion="2.9.0"
okhttp="4.11.0"
loggingInterceptor="4.10.0"
chucker-library = "3.5.2"
lottie = "5.0.3"


lifecycleCompiler = "2.8.6"
lifecycleExtensions = "2.2.0"
lifecycleCommonJava8 = "2.8.6"
lifecycleRuntimeKtx = "2.8.6"
lifecycleViewmodelKtx = "2.8.6"
pagingRuntimeKtx = "3.3.2"
localeHelperAndroid = "1.5.1"
localization = "1.2.11"
playServicesLocation = "21.3.0"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
cicerone = { module = "com.github.terrakok:cicerone", version.ref = "cicerone" }
coil = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
loading-button-android = { module = "com.github.leandroborgesferreira:loading-button-android", version.ref = "loadingButtonAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

##data module
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }
pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker-library" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }


lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleCompiler" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
locale-helper-android = { module = "com.zeugmasolutions.localehelper:locale-helper-android", version.ref = "localeHelperAndroid" }
localization = { module = "com.akexorcist:localization", version.ref = "localization" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

